### ISSUE TITLE
Having trouble uploading to Galaxy.

### ISSUE THREAD

**Issue by blancettb** [instana/ibm-instana-ansible#3]
@thedoubl3j  Hey Jake, 

I am trying to upload the collection (tar) to Galaxy but keep getting an error: 

Starting import: task_id=26124, artifact_id=26123 
Importing with galaxy-importer 0.4.0-1 
Import Task "26124" failed: No manifest found in collection 

I am using galaxy.yml and do not have a manifest. Think the documentation states I could use either or? 

Also, tried the repository import but none are found for namespace IBM. It looks like there is a 502 error being thrown. I can see IBM blockchain repositories. Wonder if they created that namespace because of the other error?  

Appreciate the help.

**Comment by thedoubl3j** [comment]
How are you building the collection @blancettb ? The manifest is generated from the galaxy.yml file when `ansible-galaxy collection build` is run from inside the collection.

**Comment by blancettb** [comment]
Yeah, I was taring it up myself. I missed it in the documentation. Thank you for your help. Was able to build and push.
