### ISSUE TITLE
The content view is showing empty 

### ISSUE THREAD

**Issue by blancettb** [instana/ibm-instana-ansible#4]
The content view for our collection in galaxy is showing up empty. We would expect our plugin (type = event_source) to show.  This is the same for the eda collection: https://galaxy.ansible.com/ansible/eda. Is there away to get our plugin to show up under content. Or maybe this is an issue for event_source typed plugins.
@thedoubl3j  

Again thanks for the help

**Comment by thedoubl3j** [comment]
Your assumption is most likely correct. This is a new type of plugin that galaxy is most likely unaware of. My guess is that it displays a list of plugin "types" that is hardcoded. While this will not land in galaxy today, I will confirm/open an issue to make sure that the plugin type will be sourced for all releases going forward of galaxy_ng/automation hub.

**Comment by blancettb** [comment]
thank you jake @arthurdm ^^^

**Comment by arthurdm** [comment]
thanks for tracking this down @blancettb.  And thanks for confirming @thedoubl3j.

**Comment by alisonlhart** [comment]
There is a workaround for this issue now available: 

To display EDA content on Ansible Automation Hub, there is an additional file needed in the collection.

Add the `meta/extensions.yml` file to the collection with the following contents:
```
extensions:
  - args:
      ext_dir: eda/plugins/event_filter
  - args:
      ext_dir: eda/plugins/event_source
```
See the [ansible.eda collection source](https://github.com/alisonlhart/event-driven-ansible/blob/github-workflows/meta/extensions.yml) for reference.
